---
title: The Black Dog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  data:
    title: data
    output: true
description: Traditional Ale | Excellent Wines | Great Food
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Traditional Ale | Excellent Wines | Great Food
url: 
baseurl: 
cover: "/img/home-about.jpg"
logo: "/img/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
